-- Semilla de corredores del Mundial de Montreal 2026 (194 corredores,
-- lista cerrada de inscritos UCI), adaptada al esquema unificado:
-- 1) inserta cada corredor en el maestro único `riders` (si no existe ya
--    con ese nombre), y 2) lo engancha a la competición 'mundial' en
--    `competition_riders` con su categoría de color y multiplicador.
--
-- Punto de partida para el maestro de corredores del resto de la app: la
-- Liga Clásicas ya tiene su propio listado clasificado en la base de
-- datos en vivo de clasicas-de-primavera (no incluido aquí porque no
-- está en el repositorio, solo en Neon) — hay que fusionarlo con este
-- antes de dar por cerrado el maestro. Ejecuta esto DESPUÉS de
-- db/schema.sql.

with raw(name, team, category, multiplier) as (
  values
    ('Aleksandr VLASOV', 'Neutral', 'verde', 2.00),
    ('Oussama Abdellah MIMOUNI', 'Argelia', 'verde', 2.00),
    ('Sebastian BERWICK', 'Australia', 'verde', 2.00),
    ('Jack Leonard HAIG', 'Australia', 'verde', 2.00),
    ('Jai HINDLEY', 'Australia', 'verde', 2.00),
    ('Michael James MATTHEWS', 'Australia', 'rosa', 1.50),
    ('Ben Alexander O''CONNOR', 'Australia', 'verde', 2.00),
    ('Michael STORER', 'Australia', 'verde', 2.00),
    ('Luke TUCKWELL', 'Australia', 'verde', 2.00),
    ('Felix GALL', 'Austria', 'verde', 2.00),
    ('Felix GROSSSCHARTNER', 'Austria', 'verde', 2.00),
    ('Patrick KONRAD', 'Austria', 'verde', 2.00),
    ('Tiesj BENOOT', 'Bélgica', 'verde', 2.00),
    ('Remco EVENEPOEL', 'Bélgica', 'amarillo', 1.00),
    ('Quinten HERMANS', 'Bélgica', 'verde', 2.00),
    ('Thibau NYS', 'Bélgica', 'rosa', 1.50),
    ('Alec SEGAERT', 'Bélgica', 'verde', 2.00),
    ('Wout VAN AERT', 'Bélgica', 'amarillo', 1.00),
    ('Maxim VAN GILS', 'Bélgica', 'verde', 2.00),
    ('Gianni VERMEERSCH', 'Bélgica', 'verde', 2.00),
    ('Kaden Luke HOPKINS', 'Bermudas', 'verde', 2.00),
    ('Nicholas NARRAWAY', 'Bermudas', 'verde', 2.00),
    ('Derrick CHAVARRIA', 'Belice', 'verde', 2.00),
    ('Henrique DA SILVA AVANCINI', 'Brasil', 'verde', 2.00),
    ('Pier-André CÔTÉ', 'Canadá', 'verde', 2.00),
    ('Derek GEE', 'Canadá', 'verde', 2.00),
    ('Hugo HOULE', 'Canadá', 'verde', 2.00),
    ('Michael Shea LEONARD', 'Canadá', 'verde', 2.00),
    ('Michael Russell WOODS', 'Canadá', 'verde', 2.00),
    ('Nickolas ZUKOWSKY', 'Canadá', 'verde', 2.00),
    ('Vicente ROJAS NARANJO', 'Chile', 'verde', 2.00),
    ('You LI', 'China', 'verde', 2.00),
    ('Santiago BUITRAGO SANCHEZ', 'Colombia', 'rosa', 1.50),
    ('Sergio Andres HIGUITA GARCIA', 'Colombia', 'verde', 2.00),
    ('Wilmar Andres PAREDES ZAPATA', 'Colombia', 'verde', 2.00),
    ('Nairo Alexander QUINTANA ROJAS', 'Colombia', 'verde', 2.00),
    ('Brandon Smith RIVERA VARGAS', 'Colombia', 'verde', 2.00),
    ('Harold Alfonso TEJADA CANACUE', 'Colombia', 'verde', 2.00),
    ('Luis Daniel OSES CAMPOS', 'Costa Rica', 'verde', 2.00),
    ('Andreas MILTIADIS', 'Chipre', 'verde', 2.00),
    ('Pavel NOVÁK', 'Chequia', 'verde', 2.00),
    ('Jakub OTRUBA', 'Chequia', 'verde', 2.00),
    ('Mathias VACEK', 'Chequia', 'verde', 2.00),
    ('Kasper ASGREEN', 'Dinamarca', 'verde', 2.00),
    ('Mikkel Norsgaard BJERG', 'Dinamarca', 'verde', 2.00),
    ('Mikkel HONORÉ', 'Dinamarca', 'verde', 2.00),
    ('Mattias Skjelmose Jennow JENSEN', 'Dinamarca', 'rosa', 1.50),
    ('Søren KRAGH ANDERSEN', 'Dinamarca', 'verde', 2.00),
    ('Andreas Lorentz KRON', 'Dinamarca', 'verde', 2.00),
    ('Mads PEDERSEN', 'Dinamarca', 'amarillo', 1.00),
    ('Michael VALGREN', 'Dinamarca', 'verde', 2.00),
    ('Kohath BARON', 'Dominica', 'verde', 2.00),
    ('Richard Antonio CARAPAZ MONTENEGRO', 'Ecuador', 'rosa', 1.50),
    ('Jefferson Alveiro CEPEDA HERNANDEZ', 'Ecuador', 'verde', 2.00),
    ('Jefferson CEPEDA ORTIZ', 'Ecuador', 'verde', 2.00),
    ('Jhonatan NARVAEZ PRADO', 'Ecuador', 'rosa', 1.50),
    ('Amanuel GHEBREIGZABHIER', 'Eritrea', 'verde', 2.00),
    ('Biniam GIRMAY', 'Eritrea', 'amarillo', 1.00),
    ('Merhawi KUDUS', 'Eritrea', 'verde', 2.00),
    ('Henok MULUEBERHAN', 'Eritrea', 'verde', 2.00),
    ('Natnael TESFATSION', 'Eritrea', 'verde', 2.00),
    ('Igor ARRIETA LIZARRAGA', 'España', 'verde', 2.00),
    ('Juan AYUSO PESQUERA', 'España', 'rosa', 1.50),
    ('Markel BELOKI FERNANDEZ', 'España', 'verde', 2.00),
    ('Marcel CAMPRUBI PIJUAN', 'España', 'verde', 2.00),
    ('Raul GARCIA PIERNA', 'España', 'verde', 2.00),
    ('Enric MAS NICOLAU', 'España', 'rosa', 1.50),
    ('Ivan ROMEO ABAD', 'España', 'verde', 2.00),
    ('Carlos VERONA QUINTANILLA', 'España', 'verde', 2.00),
    ('Madis MIHKELS', 'Estonia', 'verde', 2.00),
    ('Bruno ARMIRAIL', 'Francia', 'verde', 2.00),
    ('Louis BARRE', 'Francia', 'verde', 2.00),
    ('Alex BAUDIN', 'Francia', 'verde', 2.00),
    ('Jordan LABROSSE', 'Francia', 'verde', 2.00),
    ('Valentin PARET PEINTRE', 'Francia', 'verde', 2.00),
    ('Nicolas PRODHOMME', 'Francia', 'verde', 2.00),
    ('Paul SEIXAS', 'Francia', 'verde', 2.00),
    ('Pavel SIVAKOV', 'Francia', 'verde', 2.00),
    ('Mark Jamie DONOVAN', 'Gran Bretaña', 'verde', 2.00),
    ('Oscar ONLEY', 'Gran Bretaña', 'verde', 2.00),
    ('Finlay Xavier PICKERING', 'Gran Bretaña', 'verde', 2.00),
    ('Thomas PIDCOCK', 'Gran Bretaña', 'amarillo', 1.00),
    ('James SHAW', 'Gran Bretaña', 'verde', 2.00),
    ('Callum THORNLEY', 'Gran Bretaña', 'verde', 2.00),
    ('Alfred Brockwell WRIGHT', 'Gran Bretaña', 'verde', 2.00),
    ('Adam Richard YATES', 'Gran Bretaña', 'verde', 2.00),
    ('Gil GOMES', 'Guinea-Bisáu', 'verde', 2.00),
    ('Marco BRENNER', 'Alemania', 'verde', 2.00),
    ('Nico DENZ', 'Alemania', 'verde', 2.00),
    ('Felix ENGELHARDT', 'Alemania', 'verde', 2.00),
    ('Florian LIPOWITZ', 'Alemania', 'rosa', 1.50),
    ('Maximilian SCHACHMANN', 'Alemania', 'verde', 2.00),
    ('Georg ZIMMERMANN', 'Alemania', 'verde', 2.00),
    ('Nikiforos ARVANITOU', 'Grecia', 'verde', 2.00),
    ('Manuel Oseas RODAS OCHOA', 'Guatemala', 'verde', 2.00),
    ('Juan Mardoqueo VASQUEZ VASQUEZ', 'Guatemala', 'verde', 2.00),
    ('Fredd MATUTE BACA', 'Honduras', 'verde', 2.00),
    ('Attila VALTER', 'Hungría', 'rosa', 1.50),
    ('Ben HEALY', 'Irlanda', 'rosa', 1.50),
    ('Jamie MEEHAN', 'Irlanda', 'verde', 2.00),
    ('Ryan William MULLEN', 'Irlanda', 'verde', 2.00),
    ('Darren RAFFERTY', 'Irlanda', 'verde', 2.00),
    ('Nadav RAISBERG', 'Israel', 'verde', 2.00),
    ('Alberto BETTIOL', 'Italia', 'verde', 2.00),
    ('Mattia CATTANEO', 'Italia', 'verde', 2.00),
    ('Giulio CICCONE', 'Italia', 'verde', 2.00),
    ('Lorenzo Mark FINN', 'Italia', 'verde', 2.00),
    ('Giulio PELLIZZARI', 'Italia', 'verde', 2.00),
    ('Davide PIGANZOLI', 'Italia', 'verde', 2.00),
    ('Christian SCARONI', 'Italia', 'verde', 2.00),
    ('Matteo TRENTIN', 'Italia', 'verde', 2.00),
    ('Jo HASHIKAWA', 'Japón', 'verde', 2.00),
    ('Anton KUZMIN', 'Kazajistán', 'verde', 2.00),
    ('Daniil MARUKHIN', 'Kazajistán', 'verde', 2.00),
    ('Ali AL SHAIKHAHMED', 'Arabia Saudí', 'verde', 2.00),
    ('Kristians BELOHVOSCIKS', 'Letonia', 'verde', 2.00),
    ('Emils LIEPINS', 'Letonia', 'verde', 2.00),
    ('Martin PLUTO', 'Letonia', 'verde', 2.00),
    ('Toms SKUJINS', 'Letonia', 'verde', 2.00),
    ('Arno WALLENBORN', 'Luxemburgo', 'verde', 2.00),
    ('Edgar David CADENA MARTINEZ', 'México', 'verde', 2.00),
    ('Ulises Alfredo CASTILLO SOTO', 'México', 'verde', 2.00),
    ('Isaac DEL TORO ROMERO', 'México', 'rosa', 1.50),
    ('Jose Antonio ESCARCEGA MENDIZABAL', 'México', 'verde', 2.00),
    ('Eder FRAYRE MOCTEZUMA', 'México', 'verde', 2.00),
    ('Carlos Alfonso GARCIA TREJO', 'México', 'verde', 2.00),
    ('Maral-Erdene BATMUNKH', 'Mongolia', 'verde', 2.00),
    ('Victor LANGELLOTTI', 'Mónaco', 'verde', 2.00),
    ('Alexandre MAYER', 'Mauricio', 'verde', 2.00),
    ('Pascal EENKHOORN', 'Países Bajos', 'verde', 2.00),
    ('Daan HOOLE', 'Países Bajos', 'verde', 2.00),
    ('Menno HUISING', 'Países Bajos', 'verde', 2.00),
    ('Bart LEMMEN', 'Países Bajos', 'verde', 2.00),
    ('Bauke MOLLEMA', 'Países Bajos', 'verde', 2.00),
    ('Mathijs PAASSCHENS', 'Países Bajos', 'verde', 2.00),
    ('Mathieu VAN DER POEL', 'Países Bajos', 'amarillo', 1.00),
    ('Tim VAN DIJKE', 'Países Bajos', 'verde', 2.00),
    ('Tobias Svendsen FOSS', 'Noruega', 'verde', 2.00),
    ('Tobias Halland JOHANNESSEN', 'Noruega', 'verde', 2.00),
    ('Andreas LEKNESSUND', 'Noruega', 'verde', 2.00),
    ('Jørgen NORDHAGEN', 'Noruega', 'verde', 2.00),
    ('Anders SKAARSETH', 'Noruega', 'verde', 2.00),
    ('Embret SVESTAD-BÅRDSENG', 'Noruega', 'verde', 2.00),
    ('George BENNETT', 'Nueva Zelanda', 'verde', 2.00),
    ('Finn Lachlan Fox FISHER-BLACK', 'Nueva Zelanda', 'verde', 2.00),
    ('Ben OLIVER', 'Nueva Zelanda', 'verde', 2.00),
    ('Laurence PITHIE', 'Nueva Zelanda', 'verde', 2.00),
    ('Corbin John STRONG', 'Nueva Zelanda', 'verde', 2.00),
    ('Cristofer JURADO LOPEZ', 'Panamá', 'verde', 2.00),
    ('Mateusz GAJDULEWICZ', 'Polonia', 'verde', 2.00),
    ('Jakub KACZMAREK', 'Polonia', 'verde', 2.00),
    ('Michal KWIATKOWSKI', 'Polonia', 'verde', 2.00),
    ('Piotr PĘKALA', 'Polonia', 'verde', 2.00),
    ('Ivo Emanuel ALVES OLIVEIRA', 'Portugal', 'verde', 2.00),
    ('Tiago ANTUNES', 'Portugal', 'verde', 2.00),
    ('Afonso EULÁLIO', 'Portugal', 'verde', 2.00),
    ('Nelson OLIVEIRA', 'Portugal', 'verde', 2.00),
    ('António TOMAS MORGADO', 'Portugal', 'verde', 2.00),
    ('Amir ANSARI', 'Equipo de Refugiados', 'verde', 2.00),
    ('Mohammad GANJKHANLOU', 'Equipo de Refugiados', 'verde', 2.00),
    ('Iustin-Ioan VAIDIAN', 'Rumanía', 'verde', 2.00),
    ('Byron MUNTON', 'Sudáfrica', 'verde', 2.00),
    ('Tilen FINKŠT', 'Eslovenia', 'verde', 2.00),
    ('Gal GLIVAR', 'Eslovenia', 'verde', 2.00),
    ('Matevž GOVEKAR', 'Eslovenia', 'verde', 2.00),
    ('Luka MEZGEC', 'Eslovenia', 'verde', 2.00),
    ('Matej MOHORIC', 'Eslovenia', 'amarillo', 1.00),
    ('Jakob OMRZEL', 'Eslovenia', 'verde', 2.00),
    ('Primož ROGLIČ', 'Eslovenia', 'amarillo', 1.00),
    ('Jan TRATNIK', 'Eslovenia', 'verde', 2.00),
    ('Mihajlo STOLIĆ', 'Serbia', 'verde', 2.00),
    ('Stefan BISSEGGER', 'Suiza', 'verde', 2.00),
    ('Fabio CHRISTEN', 'Suiza', 'verde', 2.00),
    ('Jan CHRISTEN', 'Suiza', 'verde', 2.00),
    ('Marc HIRSCHI', 'Suiza', 'rosa', 1.50),
    ('Stefan KÜNG', 'Suiza', 'rosa', 1.50),
    ('Mauro SCHMID', 'Suiza', 'verde', 2.00),
    ('Martin SVRČEK', 'Eslovaquia', 'verde', 2.00),
    ('Jakob SÖDERQVIST', 'Suecia', 'verde', 2.00),
    ('Baptiste POULARD', 'Tailandia', 'verde', 2.00),
    ('Heorhii ANTONENKO', 'Ucrania', 'verde', 2.00),
    ('Antonio Eric FAGUNDEZ LIMA', 'Uruguay', 'verde', 2.00),
    ('Guillermo Thomas SILVA COUSSAN', 'Uruguay', 'verde', 2.00),
    ('Matteo JORGENSON', 'Estados Unidos', 'rosa', 1.50),
    ('Brandon MCNULTY', 'Estados Unidos', 'verde', 2.00),
    ('Neilson POWLESS', 'Estados Unidos', 'rosa', 1.50),
    ('Sean QUINN', 'Estados Unidos', 'verde', 2.00),
    ('Artem SHMIDT', 'Estados Unidos', 'verde', 2.00),
    ('Quinn SIMMONS', 'Estados Unidos', 'verde', 2.00),
    ('Kevin VERMAERKE', 'Estados Unidos', 'verde', 2.00),
    ('Lawrence WARBASSE', 'Estados Unidos', 'verde', 2.00),
    ('Samandar JANIKULOV', 'Uzbekistán', 'verde', 2.00),
    ('Orluis Alberto AULAR SANABRIA', 'Venezuela', 'verde', 2.00),
    ('Francisco Joel PEÑUELA SANDOVAL', 'Venezuela', 'verde', 2.00)
),
inserted_riders as (
  insert into riders (name, team, division)
  select distinct raw.name, raw.team, 'worldtour'
  from raw
  left join riders r on r.name = raw.name
  where r.id is null
  returning id, name
),
all_riders as (
  select id, name from riders
  union
  select id, name from inserted_riders
),
mundial as (
  select id from competitions where slug = 'mundial'
)
insert into competition_riders (competition_id, rider_id, category, multiplier)
select mundial.id, all_riders.id, raw.category, raw.multiplier::numeric(3,2)
from raw
join all_riders on all_riders.name = raw.name
cross join mundial
on conflict (competition_id, rider_id) do update
set category = excluded.category, multiplier = excluded.multiplier;
